fixes:
    - "dilhashanazeer/proj1/0/utils::proj1/utils"
    - "dilhashanazeer/proj1/0/main::proj1/main"

ignore:
    - "proj2"

coverage:
    precision: 2
    round: down
    range: "60...80"
    status:
        project:
            default:
                target: 80